### ISSUE TITLE
Issue in DeployShared/Update/Find-LatestCumulativeUpdate.ps1 - Invalid Character

### ISSUE THREAD

**Issue by fenix849** [keithga/DeploySharedLibrary#2]
The Unicode EM DASH (U+2014) on line 59 (select-string) when downloading it both Visual Studio Code and Vim see it as an invalid character.

        select-string '"([^\-\"]*)�(KB[0-9]*) \(OS Build ([0-9\.]*)\)"' -AllMatches | 

 "\p{Pd}" also matches this character and would mean not having to modify the file after download.

As in:

        select-string '"([^\-\"]*)\p{Pd}(KB[0-9]*) \(OS Build ([0-9\.]*)\)"' -AllMatches |

**Comment by keithga** [comment]
Fixed. Good catch Felix!
